<?php
namespace app\index\controller;
use think\Controller;
class  Common extends Controller
{
   
     protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cate=$this->getcate();
	
		$this->assign([
            'cate'=>$cate,
           
        ]);
    }
/**
     * 获取导航栏目
     * @return false|\PDOStatement|string|\think\Collection
     */
    private function getcate(){
        $res=db('cate')->where('pid',0)->order('sort asc,id Asc')->field('id,name,type')->select();
        foreach ($res as $k=>$v){
            $res_child=db('cate')->where('pid',$v['id'])->order('sort desc,id Asc')->field('id,name,type')->select();
            $res[$k]['child']=$res_child;
        }
        return $res;
    }
}
